### ISSUE TITLE
Specifc User scraping of new positions

### ISSUE THREAD

**Issue by robsonveras** [epctex/binance-futures-leaderboard-scraper#2]
Is there a way to invest a percentage of my total wallet amount in only new positions of a specific trader?
The idea consists in link the actor with Binance API for trading automaticaly.

**Comment by tugkan** [comment]
Hey @robsonveras ! 

Unfortunately the actor only responsible for the data retrieval from Futures Leaderboard. So there is no connection between the Binance Trader API and the project itself.

Best
