### ISSUE TITLE
Listen to specific user's positions live

### ISSUE THREAD

**Issue by yoboitel** [epctex/binance-futures-leaderboard-scraper#3]
Hey, it would be really dope to get a feature, where we can track specific users, and get a webhook everytime there's a new position opened or closed :) So we can later integrate it in a telegram bot for example.

**Comment by tugkan** [comment]
Hey @yoboitel 

Unfortunately, the actor is only for data retrieval and only logic should be created by a 3rd party which can be done by an automation tool like Zapier or a custom script. Currently, we provide `startUrls` as well. Which means that you can make it done by custom integrations.

Best

**Comment by yoboitel** [comment]
Hey, thanks for answering, ok gotchu. 
How can we know if a user's position is long or short ?
