### ISSUE TITLE
Files?

### ISSUE THREAD

**Issue by LastPlayerTR** [epctex/binance-futures-leaderboard-scraper#4]
Files?

**Comment by tugkan** [comment]
Hey @LastPlayerTR 

Can you please specify what you need from the public actor? 

Best

**Comment by LastPlayerTR** [comment]
I mean how to use that?
I cant find any API URL or files?

**Comment by tugkan** [comment]
The actor can be used here: https://apify.com/epctex/binance-futures-leaderboard
